# Generated by Django 5.2.4 on 2025-08-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="user",
        ),
    ]
